language: java

jdk:
  - oraclejdk8

# We require this because otherwise Gradle uses too much memory (https://discuss.gradle.org/t/gradle-travis-ci/11928/6)
sudo: required
dist: trusty

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/